project:
  type: book
  output-dir: ../../class/docs/pdsr/

book:
  title: "PDSR"
  author: "E.D. Gennatas"
  date: "05/22/2024"
  language: en
  google-analytics: "G-E1FN041JRR"
  repo-url: https://github.com/egenn/pdsr
  repo-subdir: src
  repo-actions: [edit, issue]
  repo-branch: master
  reader-mode: true
  chapters:
    - index.qmd
    - Preface.qmd
    - Introduction.qmd
    - Installation.qmd
    - IDEs.qmd
    - Packages.qmd
    - BasicOps.qmd
    - DataTypes.qmd
    - DataStructures.qmd
    - Indexing.qmd
    - Factors.qmd
    - part: DataIO.qmd
      chapters:
        - baseDataIO.qmd
        - datatableDataIO.qmd
        - readrDataIO.qmd
        - vroomDataIO.qmd
    - Vectorization.qmd
    - ControlFlow.qmd
    - Summarize.qmd
    - Aggregate.qmd
    - Functions.qmd 
    - LoopFunctions.qmd
    # - part: DataQueries.qmd
    #   chapters:
    #     - baseDataQueries.qmd
    #     - dtDataQueries.qmd
        # - dplyrDataQueries.qmd
        # - DuckDBDataQueries.qmd
    - part: DataFrames.qmd
      chapters: 
        - dfBasics.qmd 
        - dfReshape.qmd
        - dfJoin.qmd
    - DataTrans.qmd
    - MissingData.qmd 
    - Strings.qmd 
    - DateTime.qmd
    - SetOps.qmd
    - ClassesAndOOP.qmd
    - part: DataTable.qmd
      chapters: 
        - dtBasics.qmd
        - dtDataIO.qmd
        - dtRefSem.qmd
        - dtReshape.qmd
        - dtJoin.qmd
        - DataTableII.qmd
    - part: Tidyverse.qmd
      chapters:
        - dplyr.qmd
        - dplyrJoin.qmd
        - tidyrReshape.qmd
        - lubridate.qmd
    - part: Graphics.qmd
      chapters:
        - BaseGraphics.qmd
        - Colors.qmd
        - ggplot2.qmd
        - plotly.qmd
    - HypothesisTesting.qmd 
    - GLM.qmd
    - Profiling.qmd 
    - Optimization.qmd
    - part: IntroML.qmd
      chapters: 
        - Resampling.qmd
        - Supervised.qmd 
        - Unsupervised.qmd
    - Quarto.qmd
    - part: System.qmd
      chapters:
        - TerminalIntro.qmd
        - GitHubIntro.qmd 
    - part: Advanced.qmd
      chapters: 
        - ds.qmd
        - DuckDB.qmd
    - Resources.qmd 
    - DataPipeline.qmd
    - CrashCourse.qmd
    - References.qmd
  page-footer: "&copy; 2024 E.D. Gennatas"

bibliography: references.bib

format:
  html:
    theme:
      light: rtemis-light.scss
      dark: rtemis-dark.scss
    css: rtemis.css
    highlight-style: atom-one
    code-link: true

execute:
  freeze: auto
