project:
  type: book
  output-dir: ../_book

book:
  title: "PDSR"
  author: "E.D. Gennatas"
  date: "10/14/2022"
  google-analytics: "UA-163213745-1"
  repo-url: https://github.com/egenn/pdsr
  repo-subdir: src
  repo-actions: [edit, issue]
  repo-branch: master
  chapters:
    - index.qmd
    - Preface.qmd
    - Introduction.qmd
    - IDEs.qmd
    - Packages.qmd
    - BasicOps.qmd
    - DataTypes.qmd
    - DataStructures.qmd
    - Indexing.qmd
    - Factors.qmd
    - DataIO.qmd
    - Vectorization.qmd
    - ControlFlow.qmd
    - Summarize.qmd
    - Aggregate.qmd
    - Functions.qmd 
    - LoopFunctions.qmd
    - part: DataFrames.qmd
      chapters: 
        - dfBasics.qmd 
        - dfReshape.qmd
        - dfJoin.qmd
    - DataTrans.qmd
    - MissingData.qmd 
    - Strings.qmd 
    - DateTime.qmd
    - ClassesAndOOP.qmd
    - part: DataTable.qmd
      chapters: 
        - dtBasics.qmd
        - dtRefSem.qmd
        - dtDataIO.qmd
        - dtReshape.qmd
        - dtJoin.qmd
        - DataTableII.qmd
    - part: Tidyverse.qmd
      chapters:
        - dplyr.qmd
        - dplyrJoin.qmd
        - tidyrReshape.qmd
        - lubridateDates.qmd
    - part: Graphics.qmd
      chapters:
        - BaseGraphics.qmd
        - Colors.qmd  
        - 3xGraphics.qmd 
    - HypothesisTesting.qmd 
    - GLM.qmd
    - Profiling.qmd 
    - Optimization.qmd
    - part: IntroML.qmd
      chapters: 
        - Resampling.qmd
        - Supervised.qmd 
        - Unsupervised.qmd
    - Quarto.qmd
    - part: System.qmd
      chapters:
        - TerminalIntro.qmd 
        - GitHubIntro.qmd 
    - Resources.qmd 
    - CrashCourse.qmd
    - References.qmd
  page-footer: "&copy; 2022 E.D. Gennatas"

bibliography: references.bib

format:
  html:
    theme:
      dark: rtemis-dark.scss
      light: rtemis-light.scss
    css: bootstrap.lambdamd.css
    highlight-style: atom-one
    code-link: true
