project:
  type: book
  output-dir: ../_book

book:
  title: "PDSR"
  author: "E.D. Gennatas"
  date: "5/10/2022"
  google-analytics: "UA-163213745-1"
  # sidebar:
  #   tools:
  #     - icon: github
  #       href: https://github.com/egenn/pdsr
  repo-url: https://github.com/egenn/pdsr
  repo-subdir: src
  repo-actions: [edit, issue]
  repo-branch: master
  chapters:
    - index.qmd
    - 01_Preface.qmd
    - 02_Introduction.qmd
    - 04_Packages.qmd
    - 05_BasicOps.qmd
    - 07_Datatypes.qmd
    - 08_DataStructures.qmd
    - 09_Factors.qmd
    - 10_Indexing.qmd
    - 12_Vectorization.qmd
    - 15_InputOutput.qmd
    - 20_ControlFlow.qmd
    - 24_Summarize.qmd
    - 26_Aggregate.qmd
    - 30_Functions.qmd 
    - 32_LoopFunctions.qmd
    - 40_DataFrames.qmd 
    - 42_TableJoins.qmd
    - 44_Reshaping.qmd
    - 46_DataTrans.qmd
    - 48_StringOps.qmd 
    - 50_DateTime.qmd 
    - 52_MissingData.qmd 
    - 54_ClassesAndOOP.qmd 
    - 60_DataTable.qmd 
    - 62_dplyr.qmd
    - 70_BaseGraphics.qmd 
    - 72_3xGraphics.qmd 
    - 74_Colors.qmd 
    - 80_Profiling.qmd 
    - 82_Optimization.qmd 
    - 84_HypothesisTesting.qmd 
    - 85_GLM.qmd 
    - 86_Resampling.qmd 
    - 87_Supervised.qmd 
    - 88_Unsupervised.qmd 
    - 94_GitHubIntro.qmd 
    - 95_TerminalIntro.qmd 
    - 98_Resources.qmd 
    - 200_CrashCourse.qmd
    - 99_References.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: rtemis-light.scss
      dark: rtemis-dark.scss
    css: bootstrap.lambdamd.css
    highlight-style: atom-one
