project:
  type: book
  output-dir: ../_book

book:
  title: "PDSR"
  author: "E.D. Gennatas"
  date: "08/05/2022"
  google-analytics: "UA-163213745-1"
  # sidebar:
  #   tools:
  #     - icon: github
  #       href: https://github.com/egenn/pdsr
  repo-url: https://github.com/egenn/pdsr
  repo-subdir: src
  repo-actions: [edit, issue]
  repo-branch: master
  chapters:
    - index.qmd
    - Preface.qmd
    - Introduction.qmd
    - IDEs.qmd
    - Packages.qmd
    - BasicOps.qmd
    - DataTypes.qmd
    - DataStructures.qmd
    - Indexing.qmd
    - Factors.qmd
    - DataIO.qmd
    - Vectorization.qmd
    - ControlFlow.qmd
    - Summarize.qmd
    - Aggregate.qmd
    - Functions.qmd 
    - LoopFunctions.qmd
    - DataFrames.qmd 
    - TableJoins.qmd
    - Reshaping.qmd
    - DataTrans.qmd
    - MissingData.qmd 
    - StringOps.qmd 
    - DateTime.qmd 
    - ClassesAndOOP.qmd 
    - DataTable.qmd 
    - dplyr.qmd
    - BaseGraphics.qmd 
    - 3xGraphics.qmd 
    - Colors.qmd 
    - Profiling.qmd 
    - Optimization.qmd 
    - HypothesisTesting.qmd 
    - GLM.qmd 
    - Resampling.qmd 
    - Supervised.qmd 
    - Unsupervised.qmd 
    - GitHubIntro.qmd 
    - TerminalIntro.qmd 
    - Resources.qmd 
    - CrashCourse.qmd
    - References.qmd

bibliography: references.bib

format:
  html:
    theme:
      dark: rtemis-dark.scss
      light: rtemis-light.scss
    css: bootstrap.lambdamd.css
    highlight-style: atom-one
    code-link: true
