project:
  type: book
  output-dir: ../_book

book:
  title: "PDSR"
  author: "E.D. Gennatas"
  date: "09/18/2022"
  google-analytics: "UA-163213745-1"
  # sidebar:
  #   tools:
  #     - icon: github
  #       href: https://github.com/egenn/pdsr
  repo-url: https://github.com/egenn/pdsr
  repo-subdir: src
  repo-actions: [edit, issue]
  repo-branch: master
  chapters:
    - index.qmd
    - Preface.qmd
    - Introduction.qmd
    - IDEs.qmd
    - part: Rlang.qmd
      chapters:
        - Packages.qmd
        - BasicOps.qmd
        - DataTypes.qmd
        - DataStructures.qmd
        - Indexing.qmd
        - Factors.qmd
        - DataIO.qmd
        - Vectorization.qmd
        - ControlFlow.qmd
        - Summarize.qmd
        - Aggregate.qmd
        - Functions.qmd 
        - LoopFunctions.qmd
        - DataFrames.qmd 
        - TableJoins.qmd
        - Reshaping.qmd
        - DataTrans.qmd
        - MissingData.qmd 
        - StringOps.qmd 
        - DateTime.qmd
        - ClassesAndOOP.qmd
        - Profiling.qmd 
        - Optimization.qmd 
        - HypothesisTesting.qmd 
        - GLM.qmd 
    - part: DataTable.qmd
      chapters: 
        - DataTableI.qmd
        - dtRefSem.qmd
        - dtDataIO.qmd
        - dtMerge.qmd
        - dtReshape.qmd
        - DataTableII.qmd
    - part: Tidyverse.qmd
      chapters:
        - dplyr.qmd
        - tidyr.qmd
        - lubridate.qmd
    - part: Graphics.qmd
      chapters:
        - BaseGraphics.qmd
        - Colors.qmd  
        - 3xGraphics.qmd 
    - part: IntroML.qmd
      chapters: 
        - Resampling.qmd
        - Supervised.qmd 
        - Unsupervised.qmd
    - part: System.qmd
      chapters:
        - TerminalIntro.qmd 
        - GitHubIntro.qmd 
    - Resources.qmd 
    - CrashCourse.qmd
    - References.qmd
  page-footer: "&copy; 2022 E.D. Gennatas"

bibliography: references.bib

format:
  html:
    theme:
      light: rtemis-light.scss
      dark: rtemis-dark.scss
    css: bootstrap.lambdamd.css
    highlight-style: atom-one
    code-link: true
